  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: 
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    image: nginx:latest
    container_name: sincsuite-frontend
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

volumes:
  db_data:
